export const ITEM_ADD_ITEM_REQUEST = 'ITEM_ADD_ITEM_REQUEST';
export const ITEM_ADD_ITEM_SUCCESS = 'ITEM_ADD_ITEM_SUCCESS';
export const ITEM_ADD_ITEM_FAIL = 'ITEM_ADD_ITEM_FAIL';
export const ITEM_ADD_ITEM_RESET = 'ITEM_ADD_ITEM_RESET';

export const ITEM_GET_ITEM_DETAILS_REQUEST = 'ITEM_GET_ITEM_DETAILS_REQUEST';
export const ITEM_GET_ITEM_DETAILS_SUCCESS = 'ITEM_GET_ITEM_DETAILS_SUCCESS';
export const ITEM_GET_ITEM_DETAILS_FAIL = 'ITEM_GET_ITEM_DETAILS_FAIL';

